- name: Install Prerequsits like Stow, git, Alacritty
  hosts: localhost
  # become: true
  vars:
    - non_root_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  tasks:
  - name: Install git
    homebrew:
      state: present
      name: git
  - name: Install stow
    homebrew:
      state: present
      name: stow
  - name: Install ripgrep
    homebrew:
      state: present
      name: ripgrep
  # - name: Install Development Tools
  #   homebrew:
  #     state: present
  #     name: g++
  - name: Install neovim
    homebrew:
      state: present
      name: neovim
  - name: Install neovim package manager 
    # become: true
    # become_user: "{{ non_root_user }}"
    ansible.builtin.git:
      repo: "https://github.com/wbthomason/packer.nvim"
      dest: "~/.local/share/nvim/site/pack/packer/start/packer.nvim"
      depth: 1