- name: Install Alacritty
  hosts: localhost
  # become: true
  tasks:
  - name: Install
    block:
    # - name: Install the terminal
    #   homebrew:
    #     state: present
    #     name: alacritty
    - name: Create folder for the fonts
      become: true
      file:
        path: /Library/Fonts/JetBrainsNerdMono/
        state: directory
      # Install from https://www.jetbrains.com/lp/mono/#how-to-install
    - name: Install Jetbrains fonts
      become: true
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip
        dest: /Library/Fonts/JetBrainsNerdMono
        remote_src: yes
    rescue:
    - name:
      file:
        path: /Library/Fonts/JetBrainsMono-2.304/
        state: absent
  - name: Font cache
    shell: fc-cache -f -v

