  - name: Print user variable
    debug:
      msg: "{{ user }}"
  - name: uninstall oh my zsh
#    become: true
#    become_user: "{{ user }}"
    shell: echo "Y" | sh ~/.oh-my-zsh/tools/uninstall.sh 
    ignore_errors: true
  - name: Remove .oh-my-zsh Folder
#    become: true
#    become_user: "{{ user }}"
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "~/.oh-my-zsh"
  - name: Uninstall zsh
#    become: true
    homebrew:
      state: absent
      name: zsh
  - name: Remove .zshrc files
#    become: true
#    become_user: "{{ user }}"
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "~/.zshrc.pre-oh-my-zsh"
      - ~/.zshrc.pre-oh-my-zsh.*
      - "~/.zshrc"
      - ~/.zshrc.*

