- hosts: localhost
  tasks:
  - name: Remove .oh-my-zsh
    become: true
    become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ lookup('ansible.builtin.env', 'HOME') }}/.oh-my-zsh"
  - name: Remove .zshrc files
    become: true
    become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
      - "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc.pre-oh-my-zsh"
      - "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
  - name: Install zsh
    become: true
    dnf:
      state: present
      name: zsh
  - name: Change shell
    become: true
    shell: echo $(which zsh) | lchsh $(USER) # or use chsh instead of lchsh
  #- name: Copy default zshrc
  #  become: true
  #  become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  #  ansible.builtin.copy:
  #    src: "{{ playbook_dir }}/.zshrc"
  #    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
  - name: Install ohmyzsh
    become: true
    become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  - name: Install autosuggestion plugin for zsh
    become: true
    become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    ansible.builtin.git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions"
      dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  - name: Install syntax highlighting for zsh
    become: true
    become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    ansible.builtin.git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  - name: Update zsh plugins
    become: true
    become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    shell: sed -i 's/plugins=(git/plugins=(git zsh-autosuggestions zsh-syntax-highlighting/' ~/.zshrc
  - name: Use Vi command line typing style
    shell: bindkey -v
