- hosts: localhost
  tasks:
  - name: Remove .zshrc files
    become: true
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
      - "/root/.zshrc"
      - "/root/.zshrc.pre-oh-my-zsh"
  - name: Recursively remove ohmyzs directory
    become: true
    ansible.builtin.file:
      path: /root/.oh_my_zsh
      state: absent
  - name: Install zsh
    become: true
    dnf:
      state: present
      name: zsh
  - name: Change shell
    become: true
    shell: echo $(which zsh) | lchsh $(USER) # or use chsh instead of lchsh
  - name: Copy default zshrc
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/.zshrc"
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
  - name: Install ohmyzsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  - name: Install autosuggestion plugin for zsh
    ansible.builtin.git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions"
      dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  - name: Install syntax highlighting for zsh
    ansible.builtin.git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
