- name: Stow dotfiles
  hosts: localhost
  tasks:
  - name:
    shell: stow -d "{{ playbook_dir }}"/../../../.dotfiles/target-home/ -t ~/ .
  - name:
    become: true
    shell: stow -d "{{ playbook_dir }}"/../../../.dotfiles/target-bin/ -t /usr/local/bin/ .
