# PLAY WITH -e real_zsh_files=(true|false)
 - name: Install zsh
    become: true
    dnf:
      state: present
      name: zsh
  - name: Change shell
    become: true
    shell: echo $(which zsh) | lchsh $(USER) # or use `chsh` instead of `lchsha`
  - name: Install ohmyzsh
    become: true
    become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  - name: Install autosuggestion plugin for zsh
    become: true
    become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    ansible.builtin.git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions"
      dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  - name: Install syntax highlighting for zsh
    become: true
    become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    ansible.builtin.git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  - name: Set keybinding for zsh
    ansible.builtin.lineinfile:
      path: ~/.zshrc
      search_string: '^bindkey'
      line: bindkey -v
    when:
  - name: Install SDK Manager ASDF
    ansible.builtin.git:
      repo: https://github.com/asdf-vm/asdf.git
      dest: ~/.asdf
  - name: Update zsh plugins
    become: true
    become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    shell: sed -i 's/plugins=(git/plugins=(git asdf zsh-autosuggestions zsh-syntax-highlighting/' ~/.zshrc
  - name: Add NodeJs plugin to ASDF
    shell: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  - name: Install LTS NodeJs version globally
    shell: asdf global nodejs lts
                                    
