- hosts: localhost
####### Fedora #########
- name: Install Prerequisites
  ansible.builtin.import_playbook: tasks/fedora/install-prereq.yaml
  vars:
    non_root_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  when: ansible_facts['os_family'] == "RedHat"
- name: Install zsh
  ansible.builtin.import_playbook: tasks/fedora/install-zsh.yaml
  vars:
    non_root_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  when: ansible_facts['os_family'] == "RedHat"
- name: Install SDK manager ASDF
  ansible.builtin.import_playbook: tasks/fedora/install-sdk-manager-and-lts-node.yaml
  vars:
    non_root_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  when: ansible_facts['os_family'] == "RedHat"
 ####### MAC #########
- name: Install Prerequisites
  ansible.builtin.import_playbook: tasks/mac/install-prereq.yaml
  vars:
    non_root_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  when: ansible_facts['os_family'] == "Darwin"
- name: Install zsh
  ansible.builtin.import_playbook: tasks/mac/install-zsh.yaml
  vars:
    non_root_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  when: ansible_facts['os_family'] == "Darwin"
- name: Install SDK manager ASDF
  ansible.builtin.import_playbook: tasks/mac/install-sdk-manager-and-lts-node.yaml
  vars:
    non_root_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  when: ansible_facts['os_family'] == "Darwin"